---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: storedq-compute-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        storedq: compute
    spec:
      containers:
      - name: compute
        image: 127.0.0.1:5000/inu/storedq-cluster:${version}
        ports:
        - containerPort: 2551
        env:
          - name: IFAC
            value: eth0
          - name: ES_TRANSPORT_ADDRESS
            value: elasticsearch-discovery.default.svc.cluster.local
          - name: ES_CLUSTER_NAME
            value: myesdb
          - name: PEER_DISCOVERY_SERVICE
            value: storedq-cluster.default.svc.cluster.local
          - name: AKKA_PERSISTENCE_SERVICE
            value: cassandra3.default.svc.cluster.local
          - name: CASSANDRA_DC
            value: DC1
          - name: CLUSTER_ROLES
            value: "[compute,queryside]"
#---
#apiVersion: extensions/v1beta1
#kind: Deployment
#metadata:
#  name: storedq-queryside-deployment
#spec:
#  replicas: 1
#  template:
#    metadata:
#      labels:
#        storedq: queryside
#    spec:
#      containers:
#      - name: queryside
#        image: 127.0.0.1:5000/inu/storedq-cluster:${version}
#        ports:
#        - containerPort: 2551
#        env:
#          - name: IFAC
#            value: eth0
#          - name: PEER_DISCOVERY_SERVICE
#            value: storedq-cluster.default.svc.cluster.local
#          - name: AKKA_PERSISTENCE_SERVICE
#            value: cassandra3.default.svc.cluster.local
#          - name: ES_TRANSPORT_ADDRESS
#            value: elasticsearch-discovery.default.svc.cluster.local
#          - name: ES_CLUSTER_NAME
#            value: myesdb
#          - name: CASSANDRA_DC
#            value: DC1
#          - name: CLUSTER_ROLES
#            value: "[queryside]"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: storedq-api-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        storedq: api
    spec:
      containers:
      - name: api
        image: 127.0.0.1:5000/inu/storedq-api:${version}
        ports:
        - containerPort: 7879
        - containerPort: 2551
        env:
          - name: IFAC
            value: eth0
          - name: PEER_DISCOVERY_SERVICE
            value: storedq-cluster
          - name: ES_TRANSPORT_ADDRESS
            value: elasticsearch-discovery
          - name: ES_CLUSTER_NAME
            value: myesdb