cluster.name: inu-dc2

discovery.zen.ping.unicast.enabled: true
network.host: _non_loopback_

index:
  analysis:
    analyzer:
      whitespace_stt_analyzer:
        type: custom
        tokenizer: whitespace
        char_filter: ['role_normalizer']
    char_filter:
      role_normalizer:
        type: pattern_replace
        pattern: '(agent|customer)(\d+-\d+)\b'
        replacement: '$1'