addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.0.3")
//addSbtPlugin("se.marcuslonnberg" % "sbt-docker" % "1.2.0")
//addSbtPlugin("com.sksamuel.sbt-versions" % "sbt-versions" % "0.2.0")
addSbtPlugin("io.spray" % "sbt-revolver" % "0.7.2")
addSbtPlugin("com.typesafe.sbt" % "sbt-git" % "0.8.5")
addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.6.1")
