apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-conf
data:
  akka.conf: |
    include "application"
    akka {
      loglevel = "INFO"
      cluster {
        log-info = on
        roles = [ "compute","queryside","backend" ]

        seed-nodes = [ "akka.tcp://{{ .Values.cluster.actorsystem }}@{{ .Values.cluster.seed0 }}" ]
        http {
          management {
            hostname = 127.0.0.1
            port = {{ .Values.cluster.httpManPort }}
          }
        }
      }
      remote {
        netty.tcp {
          hostname = ${?HOST_NAME}
          port = {{ .Values.service.internalPort }}
        }
      }
    }
    storedq.cluster-name = {{ .Values.cluster.actorsystem }}
    cassandra-snapshot-store.contact-points = [ "cassandra-discovery.default.svc.cluster.local" ]
    cassandra-journal.contact-points = [ "cassandra-discovery.default.svc.cluster.local" ]

    elasticsearch {
      transport-address = "es-discovery.default.svc.cluster.local"
      client-address = "es.default.svc.cluster.local"
      transport-tcp = 9300
      client-http = 9200
      cluster-name = "myesdb"
    }